//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public System.Guid MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> MaLoaiSP { get; set; }
        public Nullable<System.Guid> MaLoaiHoa { get; set; }
        public Nullable<int> MaKT { get; set; }
        public Nullable<System.Guid> MaTK { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Size Size { get; set; }
        public virtual TypeFlower TypeFlower { get; set; }
        public virtual Statistical Statistical { get; set; }
    }
}
